Feature/carousel section
juvigh/desafio-frontend pull request #14
Opened 2023-06-20 15:08 UTC by juvigh

<p> Seção de categorias </p>
<img width="1280" alt="Captura de Tela 2023-06-19 às 21 21 00" src="https://github.com/juvigh/desafio-frontend/assets/101653937/409efb9f-3ec1-4408-8f22-89cf510a418e">
<br/> <br/>
<p> Seção de imóveis </p>
<img width="1280" alt="Captura de Tela 2023-06-19 às 21 21 22" src="https://github.com/juvigh/desafio-frontend/assets/101653937/c0a47c0f-58a1-4276-bc11-a03680433473">

2023-06-21 11:52 UTC, alanraso requested changes

2023-06-21 11:52 UTC, alanraso commented on src/components/carousel/carousel-section/card-carousel-section.tsx
> +      <Separator vertical size={8} />
O Separator não precisa ter uma escolha de tamanhos tão aberta assim. 2 ou 3 tamanhos já seriam suficientes pra montar os grids  de forma consistente.

2023-06-21 11:52 UTC, alanraso commented on src/components/carousel/carousel-section/card-carousel-section.css
> +}
Por que tem 12 de padding a esquerda e não tem a direita? Se o carrossel crescer, não acabaria ficando assimétrico o espaçamento?

2023-06-21 11:52 UTC, alanraso commented on src/components/carousel/carousel-section/card-carousel-section.css
> +    padding-left: 12px;
O espaçamento proposto era de 60px lateral na home, mas aqui está 12px, ficou com uma diferença grande. Ao menos olhando o código.

2023-06-21 11:52 UTC, alanraso commented on src/components/carousel/carousel-section/card-carousel-section.tsx
> +      <CarouselCard cardsData={cardsData} />
Não consegui refletir o que vc postou na imagem com código, porque não tem a utilização dessa `CardCarouselSection` nesse PR.

2023-06-22 12:44 UTC, alanraso commented on src/App.tsx
> +      <CardCarouselSection title="Lançamentos que você pode se interessar!" cardsData={propertyCardsData} />
Vc não acha que esse seu componente de seção se encaixa mais no cenário semelhante do "CardContainer" do que de componentização por props? Não é melhor vc enviar direto o componente que será renderizado, já tratando os dados, do que enviar um outro dado que vc criou (CardData) que fará o componente de dentro fazer uma lógica pra decidir o que renderizar? Em outras palavras, me parece mais um caso de children do que de props, o que acha?

Começando pelo `CarouselCard`: esse componente poderia receber como children os componentes que farão parte desse carrossel (e eles nem precisam ser cards):

```tsx
// Carrossel de categorias
<CarouselCard>
  {categories.map((category) => (
    <CategoryCard {...} />
  ))}
</CarouselCard>

// Carrossel de Lançamentos
<CarouselCard>
  {categories.map((category) => (
    <PropertyCard {...} />
  ))}
</CarouselCard>
```

E da mesma forma, uma seção da tela pode ter o mesmo princípio:

```tsx
<Section>
    // O código acima de categorias
</Section>

<Section>
    // O código acima de lançamentos
</Section>
```

Porque se vc usar props, vc estará transferindo a responsabilidade de decidir quais componentes vão ser renderizados para um módulo só centralizado, que vai acabar tendo muita responsabilidade no seu código. O que acha?

2023-06-22 18:41 UTC, juvigh commented on src/App.tsx
> +      <CardCarouselSection title="Lançamentos que você pode se interessar!" cardsData={propertyCardsData} />
revisei o código e concordo com a sua sugestão. No caso, o CarouselCard seria mais um "wrapper" pra renderizar os cards, certo?

2023-06-26 14:41 UTC, Japoncio3k approved these changes

2023-06-26 14:41 UTC, Japoncio3k commented on src/components/carousel/carousel-section/card-carousel-section.css
> +}
pular linha no fim do arquivo

2023-06-26 14:57 UTC, LucasGobatto approved these changes

2023-06-27 02:00 UTC, alanraso approved these changes

2023-06-27 14:34 UTC, merged